name: Node.js CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [feature/**, develop, release/**, bugfix/**, main, hotfix/**, support/**]
  pull_request:
    types: [opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "build", "sonarcloud"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          node-version: [16.x, 18.x, 20.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          architecture: [x64]
    name: BuildJS Node ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Use Node ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          cache: 'npm'
      # Install dependencies
      - name: Install dependencies Node ${{ matrix.node-version }}
        run: npm install
      # # TO COMMENT
      # - name: CI Node ${{ matrix.node-version }}
      #   run: npm ci
      # TO COMMENT
      - name: BUILD Node ${{ matrix.node-version }}
        run: npm run build --if-present
      # # TO COMMENT
      # - name: TEST Node ${{ matrix.node-version }}
      #   run: npm test

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
